### ISSUE TITLE
newer versions of klipper won't use this uf2 firmware

### ISSUE THREAD

**Issue by Riconec** [bassamanator/rp2040-zero-adxl345-klipper#1]
I get :

> This is frequently caused by running an older version of the
> firmware on the MCU(s). Fix by recompiling and flashing the
> firmware.
> 
> Your Klipper version is: v0.11.0-159-gfec7ddd8
> MCU(s) which should be updated:
> adxlpico: Current version v0.10.0-181-ge9c37688

just to let you know. I for some reason can't get uf2 file with `make` command so I am looking for uf2 for rpi pico

**Comment by bassamanator** [comment]
Will recompile in a couple of days.

**Comment by bassamanator** [comment]
@Riconec Just re-compiled both firmwares. Try the new `klipper.uf2` and let me know if it works for you. Tested fine on my end.
